### ISSUE TITLE
About caches and artifacts

### ISSUE THREAD

**Issue by ReDev1L** [ohdearapp/gitlab-ci-pipeline-for-laravel#1]
If you want caches to persist between concurrent jobs, on multiple server, you need to use remote S3 cache handler.
https://docs.gitlab.com/runner/configuration/autoscale.html#distributed-runners-caching
Artifacts are not for persisting cache between jobs.

**Comment by mattiasgeniar** [comment]
Hi @ReDev1L ,

Thanks for the heads-up! We have no desire yet to use that, but I'm very open to Pull Requests to make this more clear or add functionality.

Mattias
