### ISSUE TITLE
Upgrade to Mysql 8.0

### ISSUE THREAD

**Issue by Gil-1** [ohdearapp/gitlab-ci-pipeline-for-laravel#4]
Hello,

I know it's not really an issue but I'm tryig to add mysql8.0 to the ci config and I have a hard time doing it. I created a post on the forum of Gitlab but no answer so far.

Do you have some idea of what I could do to achieve it ?
With my try, mysql and php are not working and I don't know how to find a solution.

I explained everything in the post here :
https://forum.gitlab.com/t/gitlab-ci-php7-3-mysql8-0-result-with-command-not-found/29755

Any help would be greatly appreciated.

Thanks !

**Comment by oanhnn** [comment]
@Gil-1 I make answer for your question in Gitlab Forum.

**Comment by Gil-1** [comment]
Thank you very much !
It worked !

I reply here as my Gitlab forum's account was temporary blocked.
