### ISSUE TITLE
Pipeline Error (db-seed)

### ISSUE THREAD

**Issue by Geovica** [ohdearapp/gitlab-ci-pipeline-for-laravel#6]
Im getting an error on the build for seeding:
`9
$ mysql --version
30 mysql  Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
31 $ php artisan migrate:fresh --seed
32 In Connection.php line 669:
33                                                                                
34   SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.4' (using pa  
35   ssword: YES) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')         
36                                                                                
37 In Connector.php line 70:
38                                                                                
39   SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.17.0.4' (using pa  
40   ssword: YES)                                                                 
41                                                                                
42
Uploading artifacts...
00:03
43 storage/logs: found 3 matching files               
44 WARNING: db.sql: no matching files                 
45 Uploading artifacts to coordinator... ok            id=391733588 responseStatus=201 Created token=xvYwHHTo
46 ERROR: Job failed: exit code 1`

**Comment by mattiasgeniar** [comment]
`Access denied for user 'root'@'172.17.0.4' `

What is the config you're using (your `.env` files in CI)?

**Comment by mattiasgeniar** [comment]
Hi all,

We've long migrated away from Gitlab CI and haven't been able to support this repo as well as we should have. We'll be archiving this and putting it in read-only mode, anyone that's willing to further maintain the code is free to fork this to their own version.

Thanks for the contributions & discussions from all involved!

Mattias
