### ISSUE TITLE
Recommended image for PHP 7.4?

### ISSUE THREAD

**Issue by chrisbjr** [ohdearapp/gitlab-ci-pipeline-for-laravel#7]
Hi, have you guys upgraded to PHP 7.4 yet? We're using the image `edbizarro/gitlab-ci-pipeline-php:7.3` but it seems that the author is still having problems with his PHP 7.4 build. Would you have any recommendations for a PHP 7.4 image?

Thanks!

**Comment by freekmurze** [comment]
We've switched to using GitHub actions for our CI pipeline a while ago, so we can't help you with this question.
