### ISSUE TITLE
Cant proceed, error on uploading artifacts

### ISSUE THREAD

**Issue by ianrussel** [ohdearapp/gitlab-ci-pipeline-for-laravel#8]
I tried to use this ci file for my laravel app, but stuck when pushing to gitlab .Here is the specific errors.
`$ php -v`
`0:00
 bash: line 87: php: command not found`
`Uploading artifacts...`
`00:00
 Runtime platform                                    arch=amd64 os=linux pid=6901 revision=f100a208 version=11.6.0`
` WARNING: vendor/: no matching files           `     
 `WARNING: .env: no matching files     `              
 `ERROR: No files to upload       `                  
 `ERROR: Job failed: exit status 1`

**Comment by Gil-1** [comment]
php is not installed as the php command is not found. Strange.
I use this image right now : ```image: edbizarro/gitlab-ci-pipeline-php:7.4```
Maybe copy paste your yml config.

**Comment by mattiasgeniar** [comment]
Hi all,

We've long migrated away from Gitlab CI and haven't been able to support this repo as well as we should have. We'll be archiving this and putting it in read-only mode, anyone that's willing to further maintain the code is free to fork this to their own version.

Thanks for the contributions & discussions from all involved!

Mattias
